# Generated by Django 3.2.5 on 2022-08-09 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MojeModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przyklad', models.TextField(default='Przyladowy tekst', max_length=100)),
                ('tekscik', models.TextField(help_text='Prosze podac przykladowy tekst', max_length=20)),
                ('email_pole', models.EmailField(default='TwojAdres@email.com', max_length=40)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('wybor', models.CharField(choices=[('Pi', 'Piwo'), ('Wo', 'Wodka'), ('Wi', 'Wino'), ('Sh', 'Shot'), ('Dr', 'Drink')], default='Wybierz napoj', max_length=2)),
                ('liczba_calkowita', models.BigIntegerField(default=233)),
                ('pole_wyboru', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_wpisu', models.DateField(auto_now=True)),
                ('data_wpisu_2', models.DateTimeField(auto_now=True)),
                ('tresc_postu', models.TextField(default='Podaj tresc twojego postu.')),
                ('tytul_postu', models.CharField(default='Podaj tytul twojego postu.', max_length=150)),
                ('ilosc', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(default='Benedykt', max_length=200)),
                ('Nazwisko', models.CharField(default='Kowalski', max_length=200)),
                ('Wiek', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
